edition = "2021"
tab_spaces = 2
newline_style = "Unix"
max_width = 180
reorder_imports = true
# Unstable
# normalize_comments = true
# normalize_doc_attributes = true
# wrap_comments = true
# group_imports = "StdExternalCrate"
